# Generated by Django 5.1 on 2024-08-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealer',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
